# Generated by Django 4.0.5 on 2022-07-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tasks', '0003_alter_status_title_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='descr',
            field=models.CharField(max_length=300, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(max_length=20, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_date_to',
            field=models.DateField(db_index=True, verbose_name='дедлайн'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_from',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(db_index=True, max_length=300, verbose_name='наименование'),
        ),
    ]
