# Generated by Django 4.0.5 on 2022-07-07 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_department_profile_department'),
        ('app_tasks', '0004_alter_comment_descr_alter_status_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.profile', verbose_name='ответственный'),
        ),
    ]
