# Generated by Django 4.0.5 on 2022-07-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tasks', '0006_alter_task_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='descr',
            field=models.TextField(max_length=300, verbose_name='комментарий'),
        ),
    ]
