# Generated by Django 4.0.3 on 2022-04-27 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(verbose_name='номер телефона')),
                ('date_of_birth', models.DateTimeField(null=True, verbose_name='дата рождения')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='баланс')),
                ('status', models.CharField(default='бронзовый', max_length=11, verbose_name='статус')),
                ('q_purchases', models.PositiveIntegerField(default=0, verbose_name='количество покупок')),
                ('s_purchases', models.PositiveIntegerField(default=0, verbose_name='сумма покупок')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
