# Generated by Django 4.0.3 on 2022-04-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='q_purchases',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='s_purchases',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='номер телефона'),
        ),
    ]
